#!/usr/bin/env python

import os
import re
import numpy as np
from optparse import optionparser

import matplotlib as mpl
from matplotlib.ticker import autominorlocator
mpl.use('agg')
import matplotlib.pyplot as plt

import matplotlib.colors as mcolors
from matplotlib.patches import polygon

mpl.rcparams['axes.unicode_minus'] = false

############################################################
__version__ = "1.0"
############################################################

def weightfrompro(infile='procar'):
    """
    contribution of selected atoms to the each ks orbital
    """

    filecontents = [line for line in open(infile) if line.strip()]

    nkpts, nbands, nions = [int(xx) for xx in filecontents[1].split()
                            if xx.isdigit()]

    weights = np.asarray([line.split()[-1] for line in filecontents
                          if not re.search('[a-za-z]', line)], dtype=float)

    kpt_weight = np.asarray([line.split()[-1] for line in filecontents if 'weight' in line], dtype=float)
    
    energies = np.asarray([line.split()[-4] for line in filecontents
                            if 'occ.' in line], dtype=float)

    nspin = weights.shape[0] / (nkpts * nbands * nions)

    weights.resize(nspin, nkpts, nbands, nions)
    kpt_weight.resize(nspin, nkpts)
    energies.resize(nspin, nkpts, nbands)
    
    return energies, kpt_weight, weights

############################################################
def gradient_fill(x, y, fill_color=none, ax=none, **kwargs):
    """
    plot a line with a linear alpha gradient filled beneath it.

    parameters
    ----------
    x, y : array-like
        the data values of the line.
    fill_color : a matplotlib color specifier (string, tuple) or none
        the color for the fill. if none, the color of the line will be used.
    ax : a matplotlib axes instance
        the axes to plot on. if none, the current pyplot axes will be used.
    additional arguments are passed on to matplotlib's ``plot`` function.

    returns
    -------
    line : a line2d instance
        the line plotted.
    im : an axesimage instance
        the transparent gradient clipped to just the area beneath the curve.
    """

    line, = ax.plot(x, y, **kwargs)
    if fill_color is none:
        fill_color = line.get_color()

    # print fill_color
    zorder = line.get_zorder()
    alpha = line.get_alpha()
    alpha = 1.0 if alpha is none else alpha

    z = np.empty((100, 1, 4), dtype=float)
    rgb = mcolors.colorconverter.to_rgb(fill_color)
    z[:,:,:3] = rgb
    z[:,:,-1] = np.linspace(0, alpha, 100)[:,none]

    xmin, xmax, ymin, ymax = x.min(), x.max(), y.min(), y.max()
    im = ax.imshow(z, aspect='auto', extent=[xmin, xmax, ymin, ymax],
                   origin='lower', zorder=zorder)

    xy = np.column_stack([x, y])
    xy = np.vstack([[xmin, ymin], xy, [xmax, ymin], [xmin, ymin]])
    clip_path = polygon(xy, lw=0.0, facecolor='none', edgecolor='none', closed=true)
    ax.add_patch(clip_path)
    im.set_clip_path(clip_path)

    ax.autoscale(true)

    return line, im
############################################################
def gaussian_smearing(x, x0, sigma=0.05):
    '''
    gaussian smearing of a delta function.
    '''
    smear = np.zeros(x.size)
    condition = np.abs(x - x0) < (sigma * 5.) 
    smear[condition] = 1. / (np.sqrt(2*np.pi) * sigma) * np.exp(-(x[condition] - x0)**2 / (2*sigma**2))

    return smear

def gaussian_smearing_org(x, x0, sigma=0.05):
    '''
    gaussian smearing of a delta function.
    '''

    return 1. / (np.sqrt(2*np.pi) * sigma) * np.exp(-(x - x0)**2 / (2*sigma**2))

def generatedos(opts):
    '''
    generate dos
    '''

    ens, kptw, whts = weightfrompro(opts.procar)
    nspin, nkpts, nbands, nions = whts.shape

    emin =  ens.min()
    emax =  ens.max()
    eran = emax - emin
    emin = emin - eran * opts.extra
    emax = emax + eran * opts.extra

    xen = np.linspace(emin, emax, opts.nedos)
    # tdos = np.empty((opts.nedos, nspin))
    pdos = []

    tdos_smear = np.empty((nspin, nkpts, nbands, opts.nedos))
    for is in range(nspin):
        sign = 1 if is == 0 else -1
        for ik in range(nkpts):
            for ib in range(nbands):
                x0 = ens[is, ik, ib]
                # tdos_smear[is, ik, ib] = sign * gaussian_smearing(xen, x0, opts.sigma) * kptw[is, ik]
                tdos_smear[is, ik, ib] = sign * gaussian_smearing_org(xen, x0, opts.sigma) * kptw[is, ik]
    tdos = np.sum(tdos_smear, axis=(1, 2)).t

    if len(opts.pdosatom) != 0:

        factor = np.ones(len(opts.pdosatom))
        for ii in range(min(len(opts.pdosatom), len(opts.pdosfactor))):
            factor[ii] = opts.pdosfactor[ii]

        for ia, atoms in enumerate(opts.pdosatom):
            # p = np.zeros((opts.nedos, nspin))

            alist = np.array(atoms.split(), dtype=int)
            nlist = [x for x in alist if not x == -1]
            cmark, = np.where(alist == -1)
            for ii in cmark:
                nlist += range(alist[ii + 1], alist[ii + 2] + 1)
            nlist = [x - 1 for x in set(nlist)]

            pwhts = np.sum(whts[:,:,:, nlist], axis=-1)

            p = np.sum(pwhts[..., np.newaxis] * tdos_smear, axis=(1, 2)).t

            for is in range(nspin):
                sign = 1 if is == 0 else -1

                p[:,is] = opts.pdosoffset * ia * sign + p[:,is] * factor[ia]
                if ia == 0:
                    tdos[:,is] += opts.pdosoffset * len(opts.pdosatom)

            pdos += [p]

    return xen, tdos, pdos

############################################################
def dosplot(xen, tdos, pdos, opts):
    '''
    use matplotlib to plot band structure
    '''

    width, height = opts.figsize
    xmin, xmax = opts.xlim
    dpi = opts.dpi

    plt.style.use(opts.mpl_style)

    fig = plt.figure()
    fig.set_size_inches(width, height)
    ax = plt.subplot(111)

    lines = []
    nspin = tdos.shape[1]

    plabels = []
    lws = []
    # lcs = []
    if opts.pdosatom:
        plabels = ['p_%d' % ii for ii in range(len(opts.pdosatom))]
        lws = [0.5 for ii in range(len(opts.pdosatom))]

        for ii in range(min(len(opts.pdosatom), len(opts.pdoslabel))):
            plabels[ii] = opts.pdoslabel[ii]
        for ii in range(min(len(opts.pdosatom), len(opts.linewidth))):
            lws[ii] = opts.linewidth[ii]

    plabels += ['total']

    xen -= opts.zero
    for ip, p in enumerate(pdos):
        for ii in range(nspin):
            if opts.fill:
                line, im = gradient_fill(xen, p[:,ii], ax=ax, lw=lws[ip])
            else:
                line, = ax.plot(xen, p[:,ii], lw=lws[ip], alpha=0.6)
            if ii == 0: lines += [line]

    if opts.showtotal:
        for ii in range(nspin):
            if opts.fill:
                line, im = gradient_fill(xen, tdos[:,ii], ax=ax, # color='k',
                        lw=0.5,
                        # zorder=-1,
                        )
            else:
                line, = ax.plot(xen, tdos[:,ii], # color='k',
                        lw=0.5, alpha=0.6)
            if ii == 0: lines += [line]

    ax.set_xlabel('energy [ev]', # fontsize='small',
            labelpad=5)
    ax.set_ylabel('dos [arb. unit]', # fontsize='small',
            labelpad=10)
    ax.tick_params(which='both', labelsize='small')

    ax.set_xlim(xmin, xmax)
    if opts.ylim is not none:
        ymin, ymax = opts.ylim
        ax.set_ylim(ymin, ymax)

    # ax.set_yticklabels([])

    ax.xaxis.set_minor_locator(autominorlocator(2))
    ax.yaxis.set_minor_locator(autominorlocator(2))

    ax.legend(lines, plabels,
              loc=opts.legendloc, 
              fontsize='small',
              frameon=true,
              framealpha=0.6)

    plt.tight_layout(pad=0.20)
    plt.savefig(opts.dosimage, dpi=opts.dpi)

############################################################
def command_line_arg():
    usage = "usage: %prog [options] arg1 arg2"  
    par = optionparser(usage=usage, version= __version__)

    par.add_option("-i", '--input', 
            action='store', type="string", dest='procar',
            default='procar',
            help='location of the procar')

    par.add_option("-p", '--pdos', 
            action='append', type="string", dest='pdosatom',
            default=[],
            help='specify which atoms to plot the pdos')

    par.add_option('--pdosoffset', 
            action='store', type="float", dest='pdosoffset',
            default=0.0,
            help='offset in pdos plot')

    par.add_option("-l", '--label', 
            action='append', type="string", dest='pdoslabel',
            default=[],
            help='label of the pdos')

    par.add_option('--lloc', 
            action='store', type="string", dest='legendloc',
            default='upper right',
            help='legend location of dos plot')

    par.add_option('--fac', 
            action='append', type="float", dest='pdosfactor',
            default=[],
            help='scale factor of the pdos')

    par.add_option('-z', '--zero',
            action='store', type="float",
            dest='zero', default=0.0,
            help='energy reference of the band plot')

    par.add_option('--sigma',
            action='store', type="float",
            dest='sigma', default=0.02,
            help='smearing parameter, default 0.02')

    par.add_option('-n', '--nedos',
            action='store', type="int",
            dest='nedos', default=5000,
            help='number of point in dos plot')

    par.add_option('-o', '--output',
            action='store', type="string", dest='dosimage',
            default='dos.png',
            help='output image name, "dos.png" by default')

    par.add_option('-s', '--size', nargs=2,
            action='store', type="float", dest='figsize',
            default=(4.8, 3.0),
            help='figure size of the output plot')

    par.add_option('-x', nargs=2,
            action='store', type="float", dest='xlim',
            default=(-6, 6),
            help='x limit of the dos plot')

    par.add_option('-y', nargs=2,
            action='store', type="float", dest='ylim',
            default=none,
            help='energy range of the band plot')

    par.add_option('-e',
            action='store', type="float", dest='extra',
            default=0.05,
            help='extra energy range of the band plot')

    par.add_option('--lw',
            action='append', type="float", dest='linewidth',
            default=[],
            help='linewidth of the band plot')

    # par.add_option('--lc',
    #         action='append', type="float", dest='linecolor',
    #         default=[],
    #         help='linecolor of the band plot')

    par.add_option('--fill',
            action='store_true', dest='fill',
            default=true,
            help='fill under the dos')

    par.add_option('--nofill',
            action='store_false', dest='fill',
            help='no fill under the dos')

    par.add_option('--dpi', 
            action='store', type="int", dest='dpi',
            default=360,
            help='resolution of the output image')

    par.add_option('--tot', 
            action='store_true', dest='showtotal',
            default=true,
            help='show total dos')

    par.add_option('--notot', 
            action='store_false', dest='showtotal',
            help='not show total dos')

    par.add_option('--style', 
            action='store', type='string', dest='mpl_style',
            default='default',
            help='plot style of matplotlib. see "plt.style.available" for list of available styles.')

    par.add_option('-q', '--quiet', 
            action='store_true', dest='quiet',
            help='not show the resulting image')

    return  par.parse_args( )

############################################################
if __name__ == '__main__':
    # from time import time
    opts, args = command_line_arg()

    xen, tdos, pdos = generatedos(opts)
    # 
    # t0 = time()
    dosplot(xen, tdos, pdos, opts)
    # t1 = time()
    # print t1 - t0

    if not opts.quiet:
        from subprocess import call
        call(['feh', '-xdf', opts.dosimage])
